name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Lint
        run: |
          npm ci
          npm run lint
      - name: Run Test
        run: |
          npm run test
